default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Rails.application.credentials.rails_max_thread || 5 %>

development:
  <<: *default
  database: <%= Rails.application.credentials.postgresql[:database] %>_dev
  username: <%= Rails.application.credentials.postgresql[:username] %>
  password: <%= Rails.application.credentials.postgresql[:password] %>
  host: <%= Rails.application.credentials.postgresql[:host] %>
  port: <%= Rails.application.credentials.postgresql[:port] %>

test:
  <<: *default
  database: <%= Rails.application.credentials.postgresql[:database] %>_test
  username: <%= Rails.application.credentials.postgresql[:username] %>
  password: <%= Rails.application.credentials.postgresql[:password] %>
  host: <%= Rails.application.credentials.postgresql[:host] %>
  port: <%= Rails.application.credentials.postgresql[:port] %>

production:
  <<: *default
  database: <%= Rails.application.credentials.postgresql[:database] %>
  username: <%= Rails.application.credentials.postgresql[:username] %>
  password: <%= Rails.application.credentials.postgresql[:password] %>
  host: <%= Rails.application.credentials.postgresql[:host] %>
  port: <%= Rails.application.credentials.postgresql[:port] %>